code_style:
  image: python:3.5

  before_script:
    - pip3 install flake8

  script:
    - flake8 --statistics --verbose I1820/

docker_image:
  image: docker:latest

  # When using dind, it's wise to use the overlayfs driver for
  # improved performance.
  variables:
    DOCKER_DRIVER: overlay

  services:
    - docker:dind

  before_script:
    - docker info

  script:
    - docker build -t i1820/core .
